### PR TITLE
update multi_workers_ready?

### PR DESCRIPTION
**Pull request by gyamxxx**
#48

### CODE REVIEW

**Comment by sonots** [comment]
It shoud be written in v14.rb.

**Comment by sonots** [comment]
thanks!

**Comment by sonots** [comment]
0.9.1 is released

**Comment by sonots** [comment]
what? I though this change was committed https://github.com/sonots/fluent-plugin-record-reformer/commit/b2990a6, but it is not reflected now.

**Comment by sonots** [comment]
pushed at https://github.com/sonots/fluent-plugin-record-reformer/commit/0d8a36f8eb252209758c567cd2fe7a7b80d8b0e9

**Comment by gyamxxx** [comment]
sorry, I missed  commit (wrong user.name and user.email) and exec git reset --hard.

**Comment by sonots** [comment]
ah, okay, i was hasty.

**Pull request merged**
